### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by hundrow**
want to merge dev and main to clear up a bunch of errors

### CODE REVIEW

**Comment by molypoly** [comment]
Just a question, do we want to merge if we are still doing some final development? or will be just create another Dev branch later? I see it has no more conflicts so I have no problem with merging it.

**Comment by hundrow** [comment]
I was thinking we would make just continue working on dev after the merge. Or we could make a new dev.

**Comment by molypoly** [comment]
Sounds good to me!

**Review by molypoly — COMMENTED** [review]
Looks good

**Comment by molypoly** [comment]
Sorry just testing it out

**Pull request merged**
